version: '3.8'

services:
  app:
    build: .
    container_name: mazu_app
    ports:
      - "80:80"
    networks:
      - mazu_network
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mazu_network

volumes:
  postgres_data:
  redis_data:

networks:
  mazu_network:
    driver: bridge