version: '3.8'

services:
  app:
    build: .
    container_name: mazu_app
    ports:
      - "80:80"
    networks:
      - mazu_network
    depends_on:
      - db
  consumer:
    build: ./consumer
    ports:
      - "8000:8000"
    depends_on:
      - redis
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mazu_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

networks:
  mazu_network:
    driver: bridge